### ISSUE TITLE
Code Guide Link to Bootstrap Property Order for Stylelint Broken

### ISSUE THREAD

**Issue by chrisbo** [mdo/code-guide#265] opened 2022-05-02 21:58 UTC
The Code Guide - https://codeguide.co/ link to Bootstrap property order for Stylelint - https://github.com/twbs/stylelint-config-twbs-bootstrap/blob/master/css/index.js is broken (404).

**Comment by mdo** [comment] 2022-05-11 20:04
Duplicate of #258.

**Closed as completed by mdo** 2022-05-11 20:04 UTC
